### PR TITLE
feat: add configurable checkpid option to export

### PR DESCRIPTION
**Pull request by devmes**

### CODE REVIEW

**Comment by Apen** [comment]
Hi, thanks for this PR, im happy to see some activity here 👍 
Could you make your PR without changelog.md file please?

**Comment by Apen** [comment]
@devmes did you work on this?

**Comment by devmes** [comment]
Sorry for my late answer.
I have updated the PullRequest. There are no more conflicts now.

**Comment by Apen** [comment]
OK thanks 👍

**Pull request merged**
